apiVersion: v1
kind: Service
metadata:
  name: fabric-identity-metrics
  namespace: system
  labels:
    app.kubernetes.io/name: fabric-identity-controller
    app.kubernetes.io/component: fabric-identity-controller
    app.kubernetes.io/managed-by: kustomize
spec:
  ports:
    - name: metrics
      port: 8080
      protocol: TCP
      targetPort: metrics
  selector:
    app.kubernetes.io/name: fabric-identity-controller
